name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest
    name: ${{ matrix.package.local_path }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'AsyncEventsAWS'
            split_repository: 'mageos-async-events-aws'

#          - local_path: 'AsyncEventsAzure'
#            split_repository: 'mageos-async-events-azure'

          - local_path: 'AsyncEventsGCP'
            split_repository: 'mageos-async-events-gcp'

    steps:
      - uses: actions/checkout@v4

      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@v2.3.0"
        with:
          package_directory: 'MageOS/${{ matrix.package.local_path }}'
          repository_organization: 'mage-os'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "mage-os-ci"
          user_email: "info@mage-os.org"

      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'MageOS/${{ matrix.package.local_path }}'
          repository_organization: 'mage-os'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "mage-os-ci"
          user_email: "info@mage-os.org"
